"""The language rules and their generated consumers.

`guardrails/language-rules.json` is the one home for the rules this project states about how its own
texts are written. `scripts/gen-language-consumers.py` builds two artifacts out of it — the law bodies
the model judge is handed (`hooks/language-laws.json`) and the human rendering
(`docs/language-rules.md`) — and `guardrails/check-language-rules.py` reds drift between a committed
artifact and a fresh build, a rule claiming to be held with nothing holding it and nothing saying why,
a source pin that resolves to no file, and two rules sharing a handle.

Every red proof drives the gate over a fixture copy of the source written into a temporary directory,
so the real source is never edited.
"""
import json
import os
import subprocess
import tempfile
import unittest

from conftest import ROOT

GEN = os.path.join(ROOT, "scripts", "gen-language-consumers.py")
GATE = os.path.join(ROOT, "guardrails", "check-language-rules.py")
SOURCE = os.path.join(ROOT, "guardrails", "language-rules.json")
LAWS = os.path.join(ROOT, "hooks", "language-laws.json")
DOC = os.path.join(ROOT, "docs", "language-rules.md")


def run(script, *args, **kwargs):
    env = kwargs.get("env")
    if env is not None:
        merged = dict(os.environ)
        merged.update(env)
        env = merged
    return subprocess.run(["python3", script, *args], capture_output=True, text=True, env=env)


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def source_data():
    return json.loads(read(SOURCE))


def checkers_of(rule):
    """The checkers a rule's `catchers.model.where` names — each home's opening path."""
    out = []
    for home in rule["catchers"]["model"]["where"].split(","):
        home = home.strip()
        if home:
            checker = home.split()[0].split(":")[0]
            if checker not in out:
                out.append(checker)
    return out


def gate_module():
    """The gate module, loaded from the repository copy — the same load
    `guardrails/check-language-rules.py` does of the generator, done here of the gate itself so its
    block-drift arm can be driven directly on a fixture root without touching the real source tree."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("check_language_rules_under_test", GATE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def judge_core():
    """The judge module, loaded from the repository copy."""
    import importlib.util
    path = os.path.join(ROOT, "hooks", "register_judge_core.py")
    spec = importlib.util.spec_from_file_location("register_judge_core_under_test", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def seed(tmp, mutate):
    """A fixture source carrying one seeded fault, with both artifacts freshly generated beside it.

    Returns the gate arguments pointing at the fixture set, so the only fault the gate can find is
    the seeded one — a fixture whose artifacts were stale would red on drift instead.
    """
    data = source_data()
    mutate(data)
    fixture = os.path.join(tmp, "language-rules.json")
    with open(fixture, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    gen = run(GEN, "--source", fixture, "--out-dir", tmp)
    assert gen.returncode == 0, "the fixture artifacts did not build:\n%s" % gen.stdout
    return ["--source", fixture,
            "--laws", os.path.join(tmp, "hooks", "language-laws.json"),
            "--doc", os.path.join(tmp, "docs", "language-rules.md")]


class TestGeneratedArtifacts(unittest.TestCase):
    def test_committed_artifacts_match_a_fresh_generation(self):
        with tempfile.TemporaryDirectory() as tmp:
            r = run(GEN, "--out-dir", tmp)
            self.assertEqual(r.returncode, 0, "the generator refused to build:\n%s" % r.stdout)
            self.assertEqual(read(os.path.join(tmp, "hooks", "language-laws.json")), read(LAWS),
                             "hooks/language-laws.json differs from a fresh build — regenerate it "
                             "with scripts/gen-language-consumers.py")
            self.assertEqual(read(os.path.join(tmp, "docs", "language-rules.md")), read(DOC),
                             "docs/language-rules.md differs from a fresh build — regenerate it "
                             "with scripts/gen-language-consumers.py")

    def test_each_artifact_opens_by_naming_itself_generated(self):
        self.assertIn("GENERATED by scripts/gen-language-consumers.py", read(DOC).splitlines()[0])
        self.assertIn("GENERATED by scripts/gen-language-consumers.py", read(LAWS).splitlines()[1])

    def test_chat_laws_carry_every_rule_the_source_holds_there(self):
        # A body is keyed by the checker that runs the law and the surface it runs on, so every rule
        # the source marks as model-held on chat stands in the chat body of each checker it names.
        held = [r for r in source_data()["rules"]
                if "chat" in r["surfaces"] and r["catchers"]["model"]["status"] != "absent"]
        self.assertTrue(held, "the source marks no chat rule as model-held — the check would be vacuous")
        bodies = json.loads(read(LAWS))["bodies"]
        for rule in held:
            for checker in checkers_of(rule):
                body = bodies[checker]["chat"]
                self.assertIn(rule["catchers"]["model"]["law_text"].rstrip("."), body["text"],
                              "the %s chat body misses %s (%s)" % (checker, rule["id"], rule["name"]))
                self.assertIn(rule["reader_test"], body["text"],
                              "the %s chat body misses %s's reader test" % (checker, rule["id"]))
        for checker, by_surface in bodies.items():
            for surface, body in by_surface.items():
                self.assertEqual([law["number"] for law in body["laws"]],
                                 list(range(1, len(body["laws"]) + 1)),
                                 "the %s body on %s is not numbered from 1" % (checker, surface))

    def test_the_judge_takes_its_two_bodies_from_the_artifact(self):
        # The swap: register_judge_core.py holds the frame and reads its law text from the artifact,
        # filtering out the laws whose home is the reader's own personal layer.
        core = judge_core()
        bodies = json.loads(read(LAWS))["bodies"]
        for constant, checker, surface in (
                (core.UNIVERSAL_CHAT_LAW, "hooks/register-judge.py", "chat"),
                (core.DOCUMENT_REGISTER_LAW, "scripts/preshow-register-lint.py", "human-prose")):
            expected = "\n\n".join(law["text"] for law in bodies[checker][surface]["laws"]
                                   if not law["personal_home"])
            self.assertEqual(constant, expected,
                             "the judge's %s body differs from the artifact" % checker)
            self.assertTrue(constant.strip(), "the %s body came out empty" % checker)

    def test_the_judge_stands_down_when_the_artifact_is_unreadable(self):
        core = judge_core()
        self.assertEqual(core.load_law_body("hooks/register-judge.py", "chat",
                                            path=os.path.join(ROOT, "no-such-laws.json")), "")
        offences, error = core.judge("a text the judge never reads", "")
        self.assertEqual(offences, [])
        self.assertIn("language-laws.json", error)


class TestGateOnTheRealSource(unittest.TestCase):
    def test_gate_stays_silent_on_the_real_file(self):
        r = run(GATE)
        self.assertEqual(r.returncode, 0, "the gate red the committed source:\n%s" % r.stdout)
        self.assertIn("reach:", r.stdout)
        self.assertIn("rows scanned", r.stdout)


class TestGateRedProofs(unittest.TestCase):
    def test_reds_a_hand_edited_artifact(self):
        # DRIFT: the committed doc is generated output; a hand edit reds.
        with tempfile.TemporaryDirectory() as tmp:
            drifted = os.path.join(tmp, "language-rules.md")
            with open(drifted, "w", encoding="utf-8") as f:
                f.write(read(DOC) + "\nA sentence nobody generated.\n")
            r = run(GATE, "--doc", drifted)
            self.assertNotEqual(r.returncode, 0, "passed a hand-edited artifact:\n%s" % r.stdout)
            self.assertIn("differs from a fresh build", r.stdout)

    def test_reds_a_rule_nothing_holds_and_nothing_explains(self):
        def mutate(data):
            rule = dict(data["rules"][0])
            rule.update({
                "id": "r99",
                "name": "a seeded rule nothing holds",
                "status": "held",
                "notes": "",
                "catchers": {
                    "pattern": {"status": "absent", "where": "", "reach": ""},
                    "model": {"status": "absent", "where": "", "law_text": ""},
                    "person": {"status": "absent", "note": ""},
                },
                "sources": ["guardrails/language-rules.json:1"],
            })
            data["rules"].append(rule)

        with tempfile.TemporaryDirectory() as tmp:
            r = run(GATE, *seed(tmp, mutate))
            self.assertNotEqual(r.returncode, 0, "passed a rule nothing holds:\n%s" % r.stdout)
            self.assertIn("r99", r.stdout)
            self.assertIn("`notes` are empty", r.stdout)

    def test_reds_two_rules_under_one_name(self):
        def mutate(data):
            data["rules"][1]["name"] = data["rules"][0]["name"]

        with tempfile.TemporaryDirectory() as tmp:
            r = run(GATE, *seed(tmp, mutate))
            self.assertNotEqual(r.returncode, 0, "passed a duplicate name:\n%s" % r.stdout)
            self.assertIn("one rule, one name", r.stdout)

    def test_reds_a_source_pin_that_resolves_to_no_file(self):
        def mutate(data):
            data["rules"][0]["sources"].append("guardrails/no-such-home.md:3")

        with tempfile.TemporaryDirectory() as tmp:
            r = run(GATE, *seed(tmp, mutate))
            self.assertNotEqual(r.returncode, 0, "passed a source pin naming no file:\n%s" % r.stdout)
            self.assertIn("no-such-home.md", r.stdout)
            self.assertIn("no file stands at that path", r.stdout)

    def test_reds_a_rule_that_names_no_held_catcher_and_states_no_reason(self):
        # The arm reads every rule, whatever its status word says. `stated-only` repeats that
        # nothing runs the rule; it says nothing about why, so it discharges nothing.
        def mutate(data):
            rule = dict(data["rules"][0])
            rule.update({
                "id": "r97",
                "name": "a seeded rule with no reason",
                "status": "stated-only",
                "notes": "",
                "catchers": {
                    "pattern": {"status": "absent", "where": "", "reach": ""},
                    "model": {"status": "absent", "where": "", "law_text": ""},
                    "person": {"status": "absent", "note": ""},
                },
                "armed": ["nowhere"],
                "sources": [],
            })
            data["rules"].append(rule)

        with tempfile.TemporaryDirectory() as tmp:
            r = run(GATE, *seed(tmp, mutate), "--max-reasonless", "0")
            self.assertNotEqual(r.returncode, 0, "passed a rule with no reason:\n%s" % r.stdout)
            self.assertIn("r97", r.stdout)
            self.assertIn("state no reason", r.stdout)

    def test_a_catcher_note_states_the_reason(self):
        # The reason a reader is after is the sentence saying why nothing runs the rule, and it
        # counts where it stands: in the rule's `notes`, or in the note of one of its catchers.
        def mutate(data):
            rule = dict(data["rules"][0])
            rule.update({
                "id": "r96",
                "name": "a seeded rule a person carries",
                "status": "stated-only",
                "notes": "",
                "catchers": {
                    "pattern": {"status": "absent", "where": "", "reach": ""},
                    "model": {"status": "absent", "where": "", "law_text": ""},
                    "person": {"status": "partial",
                               "note": "telling this break from a legitimate one is a meaning call"},
                },
                "armed": ["nowhere"],
                "sources": [],
            })
            data["rules"].append(rule)

        with tempfile.TemporaryDirectory() as tmp:
            r = run(GATE, *seed(tmp, mutate), "--max-reasonless", "0")
            self.assertNotIn("r96", r.stdout,
                             "the gate named a rule whose catcher states its reason:\n%s" % r.stdout)

    def test_reds_a_rule_carrying_no_catcher_record(self):
        def mutate(data):
            data["rules"][0].pop("catchers", None)

        with tempfile.TemporaryDirectory() as tmp:
            r = run(GATE, *seed(tmp, mutate))
            self.assertNotEqual(r.returncode, 0, "passed a rule with no catchers:\n%s" % r.stdout)
            self.assertIn("carries no `catchers` record", r.stdout)

    def test_reds_a_rule_carrying_no_arming_point(self):
        def mutate(data):
            data["rules"][0].pop("armed", None)

        with tempfile.TemporaryDirectory() as tmp:
            r = run(GATE, *seed(tmp, mutate))
            self.assertNotEqual(r.returncode, 0, "passed a rule with no armed record:\n%s" % r.stdout)
            self.assertIn("carries no `armed` record", r.stdout)

    def test_red_carries_one_typed_line(self):
        # guardrails/README.md convention 1: a blocking red emits one parseable JSON object beside
        # its human lines, its `fix` the sentence a person reads.
        def mutate(data):
            data["rules"][0]["sources"].append("guardrails/no-such-home.md:3")

        with tempfile.TemporaryDirectory() as tmp:
            r = run(GATE, *seed(tmp, mutate))
            typed = [l for l in r.stdout.splitlines() if l.startswith("{")]
            self.assertEqual(len(typed), 1, "expected exactly one typed line:\n%s" % r.stdout)
            record = json.loads(typed[0])
            self.assertEqual(record["severity"], "error")
            self.assertEqual(record["code"], "language-rules")
            self.assertIn("gen-language-consumers.py", record["fix"])


class TestBlockDriftReadsEveryBlockAPageLends(unittest.TestCase):
    """`docs/language-defects.md` lends the generator two blocks: `generated:vocabulary` and
    `generated:rule-home-totals`. The block-drift arm must hold both, not just the first one it
    meets, so a hand edit inside the second block reds exactly as one inside the first does.

    Driven directly against `check_block_drift`, on a fixture root carrying an unmodified copy of the
    real page, so a corruption of one block alone proves the arm without touching the real page in
    the source tree.
    """

    RECORD_REL = os.path.join("docs", "language-defects.md")

    def _fixture_root(self, tmp, corrupt_block=None):
        """A fixture root holding a copy of the real record page, its named block corrupted."""
        text = read(os.path.join(ROOT, self.RECORD_REL))
        if corrupt_block:
            check = gate_module()
            gen = check._load_generator()
            opener = gen.block_open(corrupt_block)
            closer = gen.block_close(corrupt_block)
            start = text.find(opener) + len(opener)
            end = text.find(closer)
            self.assertGreater(end, start, "the real page carries no %s block to corrupt" % corrupt_block)
            text = text[:start] + "\n\nA sentence nobody generated.\n\n" + text[end:]
        dest = os.path.join(tmp, self.RECORD_REL)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "w", encoding="utf-8") as f:
            f.write(text)

    def test_reds_a_drift_seeded_only_in_the_second_block(self):
        # The first block (vocabulary) stands untouched; only the second (rule-home-totals) drifts.
        # Before the loop covered every block a page lends, this drift was never read.
        check = gate_module()
        gen = check._load_generator()
        with tempfile.TemporaryDirectory() as tmp:
            self._fixture_root(tmp, corrupt_block="rule-home-totals")
            problems = check.check_block_drift(gen, source_data(), tmp)
            self.assertTrue(problems, "a hand edit inside the second block a page lends passed unread")
            self.assertTrue(any("rule-home-totals" in p for p in problems),
                            "the red does not name the block that drifted:\n%s" % problems)

    def test_reds_a_drift_seeded_in_the_first_block_too(self):
        # The arm's existing coverage of the first block must survive the change.
        check = gate_module()
        gen = check._load_generator()
        with tempfile.TemporaryDirectory() as tmp:
            self._fixture_root(tmp, corrupt_block="vocabulary")
            problems = check.check_block_drift(gen, source_data(), tmp)
            self.assertTrue(problems, "a hand edit inside the first block a page lends passed unread")
            self.assertTrue(any("vocabulary" in p for p in problems),
                            "the red does not name the block that drifted:\n%s" % problems)

    def test_stays_silent_on_an_uncorrupted_fixture_root(self):
        # The fixture root carries only the record page, so the arm's other spliced pages (absent
        # here) rightly red as missing; this test reads only the record page's own two blocks.
        check = gate_module()
        gen = check._load_generator()
        with tempfile.TemporaryDirectory() as tmp:
            self._fixture_root(tmp)
            problems = check.check_block_drift(gen, source_data(), tmp)
            on_record = [p for p in problems if self.RECORD_REL in p]
            self.assertEqual(on_record, [],
                             "the arm red an unmodified copy of the real page:\n%s" % on_record)


class TestASourcePinUnderTheReadersOwnTree(unittest.TestCase):
    """What an unreadable pin means, and what it costs.

    A `sources` entry written as `~/...` names a tree the package ships to nobody. The tree's own
    root decides the verdict: where the root stands on this machine, the pin names a file that
    should be there and a missing one reds; where the root is absent, the pin is counted unread and
    the verdict line names the count and the root. Both tests drive the gate with HOME pointing at a
    temporary tree, so the answer is the same on every machine.
    """

    def _one_pin(self, pin):
        def mutate(data):
            for rule in data["rules"]:
                rule["sources"] = []
            data["rules"][0]["sources"] = [pin]
        return mutate

    def test_a_pin_missing_under_a_layer_that_stands_here_reds(self):
        with tempfile.TemporaryDirectory() as tmp:
            home = os.path.join(tmp, "home")
            os.makedirs(os.path.join(home, ".claude"))
            args = seed(tmp, self._one_pin("~/.claude/no-such-rule-home.md:3"))
            r = run(GATE, *args, env={"HOME": home})
            self.assertNotEqual(r.returncode, 0, "passed a missing pin under a standing layer:\n%s"
                                % r.stdout)
            self.assertIn("no-such-rule-home.md", r.stdout)
            self.assertIn("the reader's own layer stands at", r.stdout)

    def test_a_pin_under_an_absent_layer_is_counted_unread_and_named(self):
        with tempfile.TemporaryDirectory() as tmp:
            home = os.path.join(tmp, "home")
            os.makedirs(home)
            args = seed(tmp, self._one_pin("~/.claude/no-such-rule-home.md:3"))
            r = run(GATE, *args, env={"HOME": home})
            self.assertEqual(r.returncode, 0, "red a pin whose whole layer is absent:\n%s" % r.stdout)
            self.assertIn("leaving 1 home pins unread on this machine", r.stdout)
            self.assertIn(os.path.join(home, ".claude"), r.stdout,
                          "the verdict names the root that does not stand here")


class TestTheRuleHomeHoldsWhatTheRequirementStates(unittest.TestCase):
    """The three laws Requirement 300 states last, held against the home and its rendering.

    What these tests cannot reach is stated here rather than papered over. Requirement 300 says a
    rule whose VERDICT DIFFERS BY SURFACE holds one entry per surface. The home records no
    per-surface verdict, so no test can tell a rule with a differing verdict from a rule without
    one; what a test can hold is the shipped shape, which is stronger — every rule the home binds to
    a surface is written out in full under that surface. Requirement 300 also says a reader's
    finding enters the rulebook as a CLASS with its examples beneath it. The home records the class
    and the examples and keeps no trace of the reading that produced them, so whether a given entry
    came from one reader's stumble is outside any test here; what a test holds is that no entry
    stands as examples with no class sentence over them.
    """

    def section(self, heading):
        """The doc's region under the heading carrying exactly this text, whatever its depth.

        The page has been rendered two ways — a full entry per surface, and a per-surface index over
        one entry each — so the test reads the region and asks what stands in it rather than asking
        the renderer to keep a shape.
        """
        lines = read(DOC).splitlines()
        for i, line in enumerate(lines):
            if not line.startswith("#"):
                continue
            depth = len(line) - len(line.lstrip("#"))
            if line[depth:].strip() != heading:
                continue
            out = []
            for nxt in lines[i + 1:]:
                if nxt.startswith("#") and len(nxt) - len(nxt.lstrip("#")) <= depth:
                    break
                out.append(nxt)
            return "\n".join(out)
        return ""

    def entry_text(self, rule_id):
        """One rule's first entry in the doc, as text."""
        lines = read(DOC).splitlines()
        head = "### %s — " % rule_id
        for i, line in enumerate(lines):
            if line.startswith(head):
                out = [line]
                for nxt in lines[i + 1:]:
                    if nxt.startswith("### ") or nxt.startswith("## "):
                        break
                    out.append(nxt)
                return "\n".join(out)
        return ""

    def test_every_surface_names_every_rule_that_binds_it(self):
        data = source_data()
        for surface in ("spec-body", "human-prose", "chat", "artifact", "commit", "worker-brief"):
            section = self.section(surface)
            self.assertTrue(section.strip(), "the page carries no section for the %s surface" % surface)
            for rule in data["rules"]:
                if surface in rule["surfaces"]:
                    self.assertIn(rule["id"], section,
                                  "the %s section never names %s, which binds it"
                                  % (surface, rule["id"]))

    def test_a_personal_override_is_rendered_beside_the_shipped_value(self):
        overriding = [r for r in source_data()["rules"] if r.get("personal_override")]
        self.assertTrue(overriding, "no rule carries a personal override — the check would be vacuous")
        for rule in overriding:
            text = self.entry_text(rule["id"])
            self.assertIn("reader's own layer", text,
                          "%s carries a personal override the page never renders" % rule["id"])
            tail = text.split("reader's own layer")[1]
            for field, _value in rule["personal_override"].items():
                self.assertIn(field, tail,
                              "%s's personal layer never names the field it replaces" % rule["id"])
                for shipped in rule.get(field) or []:
                    self.assertIn(str(shipped), text,
                                  "%s's shipped %s stopped being stated beside the override"
                                  % (rule["id"], field))

    def test_a_personal_override_that_empties_a_field_keeps_the_shipped_value_stated(self):
        # The lived shape: a rule shipping one exception, and a reader's own layer taking it away.
        # Both stand on the page, so a reader of the package sees what the package ships.
        def mutate(data):
            rule = data["rules"][0]
            rule["exceptions"] = ["a contrast a reader is genuinely weighing"]
            rule["personal_override"] = {"exceptions": []}

        with tempfile.TemporaryDirectory() as tmp:
            args = seed(tmp, mutate)
            doc = read(args[args.index("--doc") + 1])
            self.assertIn("a contrast a reader is genuinely weighing", doc,
                          "the shipped exception left the page when the override arrived")
            self.assertIn("replaces the rule's `exceptions` with nothing", doc)
            r = run(GATE, *args)
            self.assertEqual(r.returncode, 0, "the gate red a rendered override:\n%s" % r.stdout)

    def test_every_entry_states_its_class_over_its_examples(self):
        rules = source_data()["rules"]
        with_examples = [r for r in rules if r.get("examples")]
        self.assertTrue(with_examples, "no rule carries examples — the check would be vacuous")
        for rule in rules:
            self.assertTrue((rule.get("rule") or "").strip(),
                            "%s carries no class sentence" % rule["id"])
        for rule in with_examples:
            text = self.entry_text(rule["id"])
            self.assertIn("**Rule.**", text)
            self.assertIn("**Examples.**", text)
            self.assertLess(text.index("**Rule.**"), text.index("**Examples.**"),
                            "%s's examples stand above the class they are evidence for" % rule["id"])

    def test_the_class_law_itself_stands_in_the_home(self):
        stated = [r for r in source_data()["rules"]
                  if "class" in r["rule"] and "example" in r["rule"]]
        self.assertTrue(stated, "no rule states that a finding enters as a class with its examples "
                                "beneath it — the law Requirement 300 names has left its home")


if __name__ == "__main__":
    unittest.main()
