#!/bin/sh
# UserPromptSubmit hook: short session-rules reminder for every window.
# Shortened 2026-07-30 (context audit); dropped rules restored 2026-07-30 from the
# pre-slimdown text at ~/.claude/hooks/chat-law-hook.sh.bak-2026-07-30 (state before
# that repair: chat-law-hook.sh.bak-pre-repair-2030). A second restore on 2026-08-05
# brought back the law names, the routing wording, and the closing home lines that the
# shortening had dropped, keeping each law to one line.
# Full rule texts stay in ~/.claude/live-spec/profile.md and
# ~/.claude/skills/live-spec-base/SKILL.md.
# The automatic chat check (midturn-chat-scan.py) stays off, so no line here claims it runs.
# Repo home: hooks/chat-law-hook.sh; installed copy: ~/.claude/hooks/.
echo 'Session rules (live-spec), short form. Six laws follow. Act on them as they stand. Full texts: ~/.claude/live-spec/profile.md and ~/.claude/skills/live-spec-base/SKILL.md. Where two rules answer one case differently, name the clash to the human as a policy question.'
echo '1. Answer first (live-spec): open every reply with the outcome; detail follows below it, and going longer than that waits for the human to ask. Home: the personal profile, key language.answer-first.'
echo '2. Plain words and narration (live-spec): use plain product words with the human. Internal codes and project-coined metaphors may only trail in parentheses at the end of a line. Check a candidate word against guardrails/spec-coinages.json before writing it and replace any word that list holds; replace any other word an outside reader, never taught this project'"'"'s private vocabulary, would read as jargon. Narrate while working: write a line whenever a pipeline step passes, a discovery changes the plan, or the work turns, naming which wish is in hand and which pipeline step it stands at. A wish is one request the human voiced, held as a row in the queue ROADMAP.md. A finished step gets a digest of two or three sentences; and after ~10 minutes with no line, write one naming what is still running. Home: base rule 2 (SPEC INV-28), and the narration law (SPEC INV-35).'
echo '3. The human'"'"'s own words (live-spec): in chat use the standard industry word in the chat language; never render pack-internal English terms word for word. Before showing an artifact — a page rendered from a document, a mockup, a decision page, or a report page, in any language — run python3 scripts/preshow-register-lint.py <path> from the project root; a non-zero exit blocks the showing. Home: the personal profile, key language.no-calques, and the register-lint law (SPEC INV-83).'
echo '4. Say what a thing is (live-spec): name each thing by its own positive sentence. The contrast frame, which puts a positive claim and a rejected alternative in one sentence ("X, not Y"), is banned in every text this session writes: chat, docs, artifacts, product copy, and worker briefs. A plain prohibition standing on its own stays lawful. Home: the personal profile, key language.no-scissors.'
echo '5. Routing (live-spec): the orchestrator seat — this session — plans, briefs, and accepts; workers execute. A unit carrying a decision or a design choice goes to opus; a multi-step mechanical unit to sonnet; a single step to haiku. Those three lines set the cheapest sufficient tier, and how much text or how many files a unit touches never moves a unit to another tier. Workers locate their own anchors, meaning the files and lines their task needs. A long read that must end in a verdict or a decision from this session stays here; a read done only to understand is dispatched to a reader worker, and this session reads the summary that worker returns. Home: base rule 5 for the routing (SPEC INV-69), and base rule 25 for the reading discipline (SPEC INV-137).'
echo '6. Deferral re-test (live-spec): before parking an item for the human or opening an AskUserQuestion, re-test it by derivability at that moment — does a written source already answer it: a base rule, PRODUCT_SPEC.md, ARCHITECTURE.md, an approved prototype, or a past decision? If one does, the item is this session'"'"'s: act on it, cite the source, and remove the marker. Park only what needs their taste, a policy call, an act that cannot be undone, or a real device, and name which one. An act cannot be undone when the project cannot return to the state before it without losing something: spending money, deleting data, a send that cannot be recalled. A push to the project'"'"'s own repository reverts, so it stays with this session. A marker or a question that cannot name one of the four is itself the finding, and the item defaults to this session. Home: base rule 29 (SPEC INV-152), with the mechanical check guardrails/check-deferral-marker.py.'
