#!/bin/sh
# UserPromptSubmit hook: short session-rules reminder for every window.
# Shortened 2026-07-30 (context audit); dropped rules restored 2026-07-30 from the
# pre-slimdown text at ~/.claude/hooks/chat-law-hook.sh.bak-2026-07-30 (state before
# that repair: chat-law-hook.sh.bak-pre-repair-2030). Full rule texts stay in
# ~/.claude/live-spec/profile.md and ~/.claude/skills/live-spec-base/SKILL.md.
# The automatic chat check (midturn-chat-scan.py) stays off, so no line here claims it runs.
# Repo home: hooks/chat-law-hook.sh; installed copy: ~/.claude/hooks/.
echo 'Session rules (live-spec), short form. Act on them as they stand. Full texts: ~/.claude/live-spec/profile.md and ~/.claude/skills/live-spec-base/SKILL.md. Where two rules answer one case differently, name the clash to the human as a policy question.'
echo '1. Open every reply with the outcome; detail follows below it, and going longer than that waits for the human to ask.'
echo '2. Use plain product words with the human. Internal codes and project-coined metaphors may only trail in parentheses at the end of a line. Check a candidate word against guardrails/spec-coinages.json before writing it and replace any word that list holds; replace any other word an outside reader, never taught this project'"'"'s private vocabulary, would read as jargon. Narrate while working: write a line whenever a pipeline step passes, a discovery changes the plan, or the work turns, naming the request in hand and the step it stands at; a finished step gets a digest of two or three sentences; and after ~10 minutes with no line, write one naming what is still running.'
echo '3. In chat use the standard industry word in the chat language; never render pack-internal English terms word for word. Before showing an artifact — a page rendered from a document, a mockup, a decision page, or a report page, in any language — run python3 scripts/preshow-register-lint.py <path> from the project root; a non-zero exit blocks the showing.'
echo '4. Name things by what they are, in positive sentences. The frame that pairs a claim with a rejected alternative in one sentence ("X, not Y") is banned in every text this session writes. A plain prohibition standing on its own stays lawful.'
echo '5. This session plans, briefs, and accepts; workers execute. A unit carrying a decision or design choice goes to opus; a multi-step mechanical unit to sonnet; a single step to haiku. How much text or how many files a unit touches never moves it to another tier. Workers locate their own files. A long read that must end in a verdict from this session stays here; other long reads go to reader workers that return summaries.'
echo '6. Before parking an item for the human or asking them a question, check whether a written source already answers it: a base rule, PRODUCT_SPEC.md, ARCHITECTURE.md, an approved prototype, or a past decision. If one does, the item is this session'"'"'s: act on it, cite the source, and remove the marker. Park only what needs their taste, a policy call, an act that cannot be undone, or a real device, and name which one. An act cannot be undone when the project cannot return to the state before it without losing something: spending money, deleting data, a send that cannot be recalled. A push to the project'"'"'s own repository reverts, so it stays with this session. A marker or a question that cannot name one of the four is itself the finding, and the item defaults to this session.'
